= New Atheism



== Gunning For God...
This document represents a summary of the stunning points that John Lennox makes in his book __"Gunning For God Why the New Atheists are Missing the Target"__. I have organized the sections(including titles) in the same manner as John's book, but will zero in on John's targets concisely so that we might use the ammunition he has provided more effectively.



== Purpose
This is meant to be a resource for anyone who may be interested in concise hard-hitting quick responses to statements made by the __New Atheism__ movement.

.The four horseman of New Atheism:
 * Richard Dawkins
 * Sam Harris
 * The late Christopher Hitchens (Now a believer)
 * Daniel Dennett

It is my hope that this short reference to John's work will help encourage a generation of **memers, twitter and facebook addicts** with similarly short attention spans.



== Attribution and Credit
**Full attribution** for these document sources must be given to **John Lennox** (With smatterings of additional authors who will be given contribution in the text.) for his beautiful work on countering this post modern challenge to the Christian faith.



== Heartfelt Thanks

John Lennox::
 __You are an inspiration and a mentor! I have spent countless hours perusing your labors and find your to be work honest, direct and relevant. Your responses flow from a lifetime of experience and passionate critical thinking. In my mind your work represent a scholarly endeavor beyond reproach. I expect C.S Lewis would feel he is with good company!__