= Gunning For God... A Summary
This document represents a summary of the stunning points that **John Lennox, Emeritus Professor of Mathematics at the University of Oxford** makes in his book __"Gunning For God Why the New Atheists are Missing the Target"__. I have organized the sections(including titles) in the same manner as John's book for clarity, but will zero in on John's targets concisely so that we might use the ammunition he has provided more effectively in daily conversation.



== Purpose
This is meant to be a resource for anyone who might be interested in concise hard-hitting responses to statements and errors in logic made by many adherents to the __New Atheism__ movement.

.The four horseman of New Atheism:
 * Richard Dawkins
 * Sam Harris
 * The late Christopher Hitchens (Now a believer)
 * Daniel Dennett



== Attribution and Credit
**Full attribution** for document sources in these sections must be given to **John Lennox** (With smatterings of additional authors who will be given contribution in the text.) for his beautiful work on countering this miso-theist post modern challenge to the Christian faith.



== Heartfelt Thanks

John Lennox::
 __You are an inspiration and a mentor! I have spent countless hours perusing your labors and find your to be work honest, direct and relevant. Your responses flow from a lifetime of experience and passionate critical thinking. In my mind your work represents a scholarly endeavor beyond reproach. I expect C.S Lewis would feel he is with good company!__