= Why the Aggression?

One must ask, why the onset of aggressive atheism? In Gunning for God, John Lennox again seems to have hit the target dead center.

[quote, John Lennox: Gunning for God Why the New Atheists are Missing the Target: 2011: pg 17 - 18]
____
Something appears to have snapped. And it has: The Twin Towers on 9/11. According to the leading German weekly news magazine **Der Spiegel**, it was that horrific event in 2001 that gave birth to the New Atheism. A cover article entitled "God is to blame for everything" says: "without the attacks on New York and Washington, there would be no New Atheism." In a later interview with the same magazine, Dawkins says that 9/11 "radicalised" him, thus confirming his earlier statement:

#"My last vestige of "hands-off religion" respect disappeared in the smoke and choking dust of September 11, 2001, followed by the "National Day of Prayer", when prelates and pastors did their tremulous Martin Luther King impersonation and urged people of mutually incompatible faiths to hold hands, united in homage to the very force that caused the problem in the first place."#

The logic is simple. "Imagine with John Lennon," says Dawkins, " a world without religion. Imagine no suicide bombers, no 9/11, no 7/7, no Crusades, no witch-hunts, no Gunpowder plot, no Indian partition, no Israeli/Palestinian wars, no Serb/Croat/Muslim massacres, no persecution of Jews as 'Christ Killers", no NOrthern Ireland 'troubles', no 'honour killings', no shiny-suited bouffant-haired televangelists fleecing gullible people of their money ('God wants you to give till it hurts'). Imagine no Taliban to blow up ancient statues, no public beheadings of blasphemers, no flogging of female skin for the crime of showing an inch of it."...

...Most of us have no hesitation in agreeing with the New Atheists that there are problems, major problems, with aspects of religion. How could we "respect" religious extremists that encourage young men and women to become living bombs in order to gain instant access to paradise? The New Atheists are quite right in drawing attention to this kind of thing, especially in societies that are in danger of having public discourse paralysed by political correctness...

...Well then, if religion is the problem, then the solution is obvious, say the New Atheists: get rid of religion. Civilized society, they say, can no longer afford the luxury of smiling indulgently at religion that has become far to dangerous and extreme for such complacency. It must therefore be eliminated; and Nobel Laureate Steven Weinberg, for one, has no hesitation in saying so:

#"The world needs to wake up from the long nightmare of religion... *Anything* we scientists can do to weaken the hold of religion should be done, and may in fact be our greatest contribution to civilization."#

That is the New Atheists' stated goal in a nutshell; and the observant reader will not miss the totalitarian sounding word "anything" in Weinberg's statement. Dawkins states the goal this way:

#"If this book works as I intend, religious readers who open it will be atheists when they put it down."#

He wants not only to #rally the faithful (atheists) and to encourage them to "come out" for their faith (for such it is, despite their protests to the contrary as we shall see), but also to proselytize - to "raise the consciousness" of others.#
____

