[[historicity-of-jesus]]
= Historicity of Jesus

Common Question:: What kind of historical evidence exists from non-Christian sources that demonstrate Jesus was in fact a real person?

== What is the Academic Consensus?

There are few fringe higher academics of history who debate if Christ lived, or was in fact a real person. The shear volume of documented evidence and sources that contain the following facts are beyond a reasonable doubt:

 * He existed as a **real person**
 * He was baptized by **John the Baptist**
 * Was brought before the Roman prefect(Governor) **Pontius Pilate**
 * Died by **crucifixion**

Even hard line skeptics such as **Bart Erhman** the well known Atheist verifies **Christ as a real person**.

The items that are disputed by critics are:

* Nativity of Jesus (Virgin Birth)
* Miraculous Events (Water to wine, walking on water, healing lepers, raising the dead, healing the deaf and blind, and the resurrection)
* Several details pertaining to the crucifixion

[quote, Joseph Cayouette]
____
To say it quite directly, individuals choose not to believe in miracles in spite of the evidence that Christianity started at all! **If Christ had remained in the ground**, would His disciples have ever gone out again to preach his message? **Would they have even thought of such a thing? Up until that point everyone that died stayed dead.** They had been *hiding* in the upper room until He visited them. Christianity would have been dead in the water without the evidence He provided to those first few individuals that His power over nature and His power over death pointed to the very fact that He was God.
____


Jesus always used *evidence* for his followers, and those whom He comforted via miracles.

[quote, John 20: 27 - 30]
____
27 Then he said to Thomas, “Put your finger here, and see my hands; and put out your hand, and place it in my side. Do not disbelieve, but believe.” 28 Thomas answered him, #“My Lord and my God!”# 29Jesus said to him, “Have you believed because you have seen me? Blessed are those who have not seen and yet have believed.” 30 Now #Jesus did many other signs in the presence of the disciples, which are not written in this book; 31 but these are written so that you may believe that Jesus is the Christ, the Son of God, and that by believing you may have life in his name.#
____

The external evidence for the existence of Jesus will be examined in depth in the following sections.
